// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLiPhongKham.Models;

#nullable disable

namespace QuanLiPhongKham.Migrations
{
    [DbContext(typeof(QuanLiPhongKhamContext))]
    [Migration("20251113040325_AddUserTable")]
    partial class AddUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLiPhongKham.Models.BacSi", b =>
                {
                    b.Property<int>("BacSiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BacSiID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BacSiId"));

                    b.Property<string>("ChuyenKhoa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BacSiId")
                        .HasName("PK__BacSi__5B2D075426589883");

                    b.ToTable("BacSi", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.BenhNhan", b =>
                {
                    b.Property<int>("BenhNhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BenhNhanId"));

                    b.Property<string>("DiaChi")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GioiTinh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BenhNhanId")
                        .HasName("PK__BenhNhan__151050A6BAF493D5");

                    b.ToTable("BenhNhan", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.ChiTietDonThuoc", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ChiTietID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"));

                    b.Property<int>("DonThuocId")
                        .HasColumnType("int")
                        .HasColumnName("DonThuocID");

                    b.Property<string>("LieuLuong")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenThuoc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietD__B117E9EAFD6AE700");

                    b.HasIndex("DonThuocId");

                    b.ToTable("ChiTietDonThuoc", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.DonThuoc", b =>
                {
                    b.Property<int>("DonThuocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DonThuocID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonThuocId"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LichHenId")
                        .HasColumnType("int")
                        .HasColumnName("LichHenID");

                    b.Property<DateTime?>("NgayLap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("DonThuocId")
                        .HasName("PK__DonThuoc__C8A3B4B0234CCB1F");

                    b.HasIndex("LichHenId");

                    b.ToTable("DonThuoc", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.LichHen", b =>
                {
                    b.Property<int>("LichHenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LichHenID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichHenId"));

                    b.Property<int>("BacSiId")
                        .HasColumnType("int")
                        .HasColumnName("BacSiID");

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    b.Property<DateTime>("NgayHen")
                        .HasColumnType("datetime");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LichHenId")
                        .HasName("PK__LichHen__F92991B6A9C2395B");

                    b.HasIndex("BacSiId");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("LichHen", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.ThanhToan", b =>
                {
                    b.Property<int>("ThanhToanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ThanhToanID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ThanhToanId"));

                    b.Property<int>("BenhNhanId")
                        .HasColumnType("int")
                        .HasColumnName("BenhNhanID");

                    b.Property<string>("HinhThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayThanhToan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ThanhToanId")
                        .HasName("PK__ThanhToa__24A8D6841A3C0A43");

                    b.HasIndex("BenhNhanId");

                    b.ToTable("ThanhToan", (string)null);
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.ChiTietDonThuoc", b =>
                {
                    b.HasOne("QuanLiPhongKham.Models.DonThuoc", "DonThuoc")
                        .WithMany("ChiTietDonThuocs")
                        .HasForeignKey("DonThuocId")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDo__DonTh__5535A963");

                    b.Navigation("DonThuoc");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.DonThuoc", b =>
                {
                    b.HasOne("QuanLiPhongKham.Models.LichHen", "LichHen")
                        .WithMany("DonThuocs")
                        .HasForeignKey("LichHenId")
                        .IsRequired()
                        .HasConstraintName("FK__DonThuoc__LichHe__52593CB8");

                    b.Navigation("LichHen");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.LichHen", b =>
                {
                    b.HasOne("QuanLiPhongKham.Models.BacSi", "BacSi")
                        .WithMany("LichHens")
                        .HasForeignKey("BacSiId")
                        .IsRequired()
                        .HasConstraintName("FK__LichHen__BacSiID__4E88ABD4");

                    b.HasOne("QuanLiPhongKham.Models.BenhNhan", "BenhNhan")
                        .WithMany("LichHens")
                        .HasForeignKey("BenhNhanId")
                        .IsRequired()
                        .HasConstraintName("FK__LichHen__BenhNha__4D94879B");

                    b.Navigation("BacSi");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.ThanhToan", b =>
                {
                    b.HasOne("QuanLiPhongKham.Models.BenhNhan", "BenhNhan")
                        .WithMany("ThanhToans")
                        .HasForeignKey("BenhNhanId")
                        .IsRequired()
                        .HasConstraintName("FK__ThanhToan__BenhN__59063A47");

                    b.Navigation("BenhNhan");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.BacSi", b =>
                {
                    b.Navigation("LichHens");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.BenhNhan", b =>
                {
                    b.Navigation("LichHens");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.DonThuoc", b =>
                {
                    b.Navigation("ChiTietDonThuocs");
                });

            modelBuilder.Entity("QuanLiPhongKham.Models.LichHen", b =>
                {
                    b.Navigation("DonThuocs");
                });
#pragma warning restore 612, 618
        }
    }
}
